FROM ubuntu:jammy AS builder

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential \
      git \
      wget \
      devscripts \
      debhelper-compat \
      libpugixml-dev \
      libzip-dev \
      libssl-dev \
      libcurl4-gnutls-dev \
      ca-certificates

WORKDIR /usr/src

RUN git clone https://github.com/steinarb/libgourou-debian.git

WORKDIR /usr/src/libgourou-debian/packaging

RUN dpkg-buildpackage -us -uc -d

FROM ubuntu:jammy AS release

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      bash \
      libpugixml1v5 \
      libzip4 \
      libssl3 \
      libcurl4-gnutls-dev && \
    apt-get autoclean && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

COPY --from=builder /usr/src/libgourou-debian/libgourou_*.deb ./

RUN ls -l /tmp

RUN dpkg -i libgourou_*.deb || apt-get -y -f install

COPY scripts/ /home/libgourou/

WORKDIR /home/libgourou

ENTRYPOINT ["/bin/bash", "/home/libgourou/entrypoint.sh"]
