# build apps
FROM alpine:3.21 AS builder

# branch or tag of libgourou to build (pin for reproducible images)
ARG LIBGOUROU_REF=master

RUN apk add --no-cache \
    g++ \
    make \
    git \
    bash \
    ca-certificates \
    pugixml-dev \
    openssl-dev \
    curl-dev \
    libzip-dev

WORKDIR /usr/src

RUN git clone --branch "${LIBGOUROU_REF}" --depth 1 \
    https://forge.soutade.fr/soutade/libgourou.git \
  && cd libgourou \
  && make BUILD_STATIC=1

# copy from builder to runtime image
FROM alpine:3.21

RUN apk add --no-cache \
    bash \
    libcurl \
    libzip \
    pugixml

COPY --from=builder /usr/src/libgourou/utils/acsmdownloader \
                    /usr/src/libgourou/utils/adept_activate \
                    /usr/src/libgourou/utils/adept_remove \
                    /usr/src/libgourou/utils/adept_loan_mgt \
                    /usr/local/bin/

WORKDIR /home/libgourou
COPY scripts .

ENTRYPOINT ["/bin/bash", "/home/libgourou/entrypoint.sh"]
