FROM ubuntu:jammy AS builder

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive TZ="America\Los_Angeles" \
  apt-get install -y \
  build-essential \
  bash \
  git \
  wget \
  libzip-dev \
  libssl-dev \
  libcurl4-gnutls-dev \
  libpugixml-dev

WORKDIR /usr/src
# RUN apt-get install -y valgrind

RUN git clone git://soutade.fr/libgourou.git \
  && cd libgourou \
  && make BUILD_STATIC=1 STATIC_UTILS=1

FROM ubuntu:jammy as release

COPY --from=builder /usr/src/libgourou/utils/acsmdownloader \
                    /usr/src/libgourou/utils/adept_activate \
                    /usr/src/libgourou/utils/adept_remove \
                    /usr/src/libgourou/utils/adept_loan_mgt \
                    /usr/local/bin/

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive TZ="America\Los_Angeles" \ 
  && apt-get install -y \
  libpugixml1v5 \
  libzip4 \
  libssl3 \
  libcurl4-gnutls-dev \
  && apt-get autoclean \
  && rm -rf /var/lib/apt/lists/*

COPY scripts /home/libgourou
WORKDIR /home/libgourou
ENTRYPOINT ["/bin/bash", "/home/libgourou/entrypoint.sh"]